
package com.webservices.client.namesClient.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NameService", targetNamespace = "http://ws.names.webservices.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NameService {


    /**
     * 
     * @param model
     * @return
     *     returns com.webservices.client.namesClient.ws.ModelResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://ws.names.webservices.com/", className = "com.webservices.client.namesClient.ws.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://ws.names.webservices.com/", className = "com.webservices.client.namesClient.ws.GetUserNameResponse")
    public ModelResponse getUserName(
        @WebParam(name = "model", targetNamespace = "")
        Modelrequest model);

}
