
package com.webservices.client.namesClient.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NameServiceImplService", targetNamespace = "http://ws.names.webservices.com/", wsdlLocation = "http://localhost:8090/nameServices?wsdl")
public class NameServiceImplService
    extends Service
{

    private final static URL NAMESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NAMESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName NAMESERVICEIMPLSERVICE_QNAME = new QName("http://ws.names.webservices.com/", "NameServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/nameServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NAMESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        NAMESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public NameServiceImplService() {
        super(__getWsdlLocation(), NAMESERVICEIMPLSERVICE_QNAME);
    }

    public NameServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NAMESERVICEIMPLSERVICE_QNAME, features);
    }

    public NameServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, NAMESERVICEIMPLSERVICE_QNAME);
    }

    public NameServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NAMESERVICEIMPLSERVICE_QNAME, features);
    }

    public NameServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NameServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NameService
     */
    @WebEndpoint(name = "NameServiceImplPort")
    public NameService getNameServiceImplPort() {
        return super.getPort(new QName("http://ws.names.webservices.com/", "NameServiceImplPort"), NameService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NameService
     */
    @WebEndpoint(name = "NameServiceImplPort")
    public NameService getNameServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.names.webservices.com/", "NameServiceImplPort"), NameService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NAMESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw NAMESERVICEIMPLSERVICE_EXCEPTION;
        }
        return NAMESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
